### ISSUE TITLE
df_spec() ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Olauwers** [gaprieto/multitaper#5]
When generating an MTSpec object, and subsequently calling df_spec() results in a ValueError: too many values to unpack
Example code:

import multitaper
import numpy as np

psd = multitaper.mtspec.MTSpec(np.random.randn(2**7),nw=4,dt=1)
psd.df_spec()

It seems that df_spec() is returning an additional frequency attribute.

**Comment by gaprieto** [comment]
I will correct this for the following version.
